### ISSUE TITLE
Problem with platform.io and ArduinoOTA (Example BasicOTA.ino)

### ISSUE THREAD

**Issue by chessweb01** [platformio/platformio-examples#12]
The example BasicOTA.ino that illustrates over the air firmware updates of ESP8266 modules compiles with Arduino IDE 1.6.8 but not with Atom/platform.io. 

With the latter I get "error: 'class ArduinoOTAClass' has no member named 'getCommand'". platform.io has an obsolete version of the ArduinoOTA class. On the other hand, Arduino's version is more recent and has a getCommand method.

I'm positive that Atom, platform.io, and all packages are up to date on my computer. I'm working with NodeMCU v1.0.

Work around: 
Locate Arduino's version of the ArduinoOTA class and put it into the local lib folder (lib/ArduinoOTA/ArduinoOTA.h, .cpp) of the platform.io project.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by scropion86** [comment]
i have the same issue , even after applying the workaround still not compiling
and below error is appearing

```



pio
lib
ArduinoOTA.cpp
ArduinoOTA.h
readme.txt
src
main.cpp
.gitignore
.travis.yml
platformio.ini
main.cpp
platformio.ini
 1
 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html
 
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
 
2.0 s
platformio run
src\main.cpp:35:20: error: 'class ArduinoOTAClass' has no member named 'getCommand'
if (ArduinoOTA.getCommand() == U_FLASH)
^
Compiling .pioenvs\esp12e\FrameworkArduino\base64.o
*** [.pioenvs\esp12e\src\main.o] Error 1
 [ERROR] Took 1.58 seconds
 
```

**Comment by ivankravets** [comment]
Please open new issue here https://github.com/platformio/platform-espressif8266 if you still experience this issue.
